logging:
  level:
    org.springframework.ai.chroma: TRACE
    org.springframework.web.client: TRACE
    org.springframework.web.client.RestTemplate: TRACE
    org.springframework.web.client.RestClient: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: TRACE

server:
  port: 8083

spring:
  application:
    name: ai-orchestrator
  data:
    redis:
      host: localhost
      port: 6379
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-3-small
    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 9002
        initialize-schema: true
        tenant-name: default_tenant
        database-name: default_database
        collection-name: docs
  cloud:
    aws:
      credentials:
        access-key: ${MINIO_USER}
        secret-key: ${MINIO_PASS}
      region:
        static: eu-west-1
      s3:
        endpoint: http://localhost:9000  # http://host.docker.internal:9000 Docker Desktop
        path-style-access-enabled: true



ai:
  providers:
    openai:
      base-url: https://api.openai.com
      api-key: ${OPENAI_API_KEY}
      models:
        gpt-4o-mini:
          temperature: 0.7
          max-tokens: 8192
        gpt-4o:
          temperature: 0.7
          max-tokens: 16384

    groq:
      base-url: https://api.groq.com/openai
      api-key: ${GROQ_API_KEY}
      models:
        "[llama-3.1-70b]": #necesario para escapar el punto
          temperature: 0.8
          max-tokens: 131072
        gemma-2-27b:
          temperature: 0.9
          max-tokens: 8192
        "[llama-3.3-70b-versatile]":
          temperature: 0.6
          max-tokens: 4096

    deepseek:
      base-url: https://api.deepseek.com
      api-key: ${DEEPSEEK_API_KEY}
      models:
        deepseek-chat:
          temperature: 0.6
          max-tokens: 4096

  default-provider: groq
  default-model: llama-3.3-70b-versatile

s3:
  questions-bucket: questionsbucket