server:
  port: 8082

spring:
  application:
    name: ticket-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ticketing
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true # Crea la tabla de Flyway si no existe
  kafka:
    bootstrap-servers: localhost:9092